[build]
  publish = ".next"

[functions]
  # Note: Netlify Free tier has a 10-second timeout limit
  # The /api/generate endpoint takes ~45 seconds and will timeout
  # Use /api/generate-light with client-side text extraction instead
  directory = ".netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Environment variables should be set in Netlify dashboard 